name: Node.js CI with Docker Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Make Jest executable
        run: chmod +x node_modules/.bin/jest

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Docker build
        run: |
          docker build -t myapp:latest .

      - name: Push Docker images to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker tag myapp:latest ${DOCKER_USERNAME}/myapp:latest
          docker push ${DOCKER_USERNAME}/myapp:latest
